### PR TITLE
fix: updates with no changes should fail

### LINKED ISSUE #49: dsfs.CreateDataset: attempting to update a dataset that changes nothing must fail
When calling `CreateDataset`, after a successful call to `prepareDataset` we should check any dataset that has a `Previous` entry, verifying at least one of the following fields has changed between the entry at `Previous` and the dataset to be saved:

```
Structure
Meta
Transform
Vis
DataPath
```
This reminds me of the work we're doing on datasetDiffer, and we should leverage that here.

### Steps to Complete
* [x] either ship #48, or do this while shipping 48
* [x] use dsfs to load a fully de-referenced version of the previous dataset for examination
* [x] use the output of datasetDiff to check for lack of changes
* [x] add tests that attempt to submit unchanged datasets to create, make sure they fail.

### PR DESCRIPTION
**Pull request by osterbit**
closes #49

### CODE REVIEW

File: dsfs/dataset.go [hunk 1]
```diff
@@ -263,6 +265,27 @@ func prepareDataset(store cafs.Filestore, ds *dataset.Dataset, df cafs.File, pri
 	return memfs.NewMemfileBytes("data."+ds.Structure.Format.String(), data), nil
 }
 
+// confirmChangesOc
```
Comment (b5) [inline dsfs/dataset.go]: mind cleaning up this stray comment?

File: dsfs/testdata/cities_no_commit_title.json [hunk 2]
```diff
@@ -38,5 +38,10 @@
         ]
       }
     }
+  },
+  "visconfig": {
+    "kind": "qri:vc:0",
```
Comment (b5) [inline dsfs/testdata/cities_no_commit_title.json]: keep in mind `"kind" : "qri:vc:0` should now be `"qri" : "vc:0"`

File: dsfs/dataset.go [hunk 3]
```diff
@@ -263,6 +265,27 @@ func prepareDataset(store cafs.Filestore, ds *dataset.Dataset, df cafs.File, pri
...
+	if err != nil {
+		return fmt.Errorf("error loading previous dataset: %s", err.Error())
+	}
+	diffMap, err := datasetDiffer.DiffDatasets(prev, ds)
+	if err != nil {
+		return err
+	}
+
+	if datasetDiffer.MapDiffsToString(diffMap) == "" {
+		return fmt.Errorf("cannot record changes if no changes occured")
```
Comment (b5) [inline dsfs/dataset.go]: Not necessary right now, but in the future we should try to make error messages as clear and human-readable as possible while still being precise, But before we get too deep on error changes we should all figure out an approach & style of writing errors that works across the board. Just want to bring this to your attention now. We might also want to declare an `ErrNoChanges` variable in datasetDiffer to detect this error elsewhere.
